### ISSUE TITLE
Fails to compile with GHC 7.0.4 and GHC 7.2.2

### ISSUE THREAD

**Issue by hvr** [vincenthz/hs-hourglass#15]
As you may know already due to #8 `hourglass` fails to build with GHC 7.0/7.2, and by now you already know I added `base >= 4.5` constraints to previous releases in order to keep Cabal from running into bad install-plans, and give it a chance to choose alternative install-plans avoiding `hourglass` for GHC 7.0/7.2

See also https://ghc.haskell.org/~hvr/buildreports/hourglass.html

Please add a `base >= 4.5` constraint to future releases (unless #8 gets fixed by then)

**Comment by NicolasDP** [comment]
I suppose this #16 might fix your issue with this old version of GHC.

**Comment by hvr** [comment]
@NicolasDP #16 looks good to me
