### ISSUE TITLE
export dateAddPeriod

### ISSUE THREAD

**Issue by cocreature** [vincenthz/hs-hourglass#17]
In Data.Hourglass.Diff there is the dateAddPeriod but sadly that module is hidden and the method is not reexported. As timeAdd is exported it would be nice if this could also be exported.

**Comment by anton-dessiatov** [comment]
I second this, it would be great if I could just add 20 years or something like this to arbitrary DateTime.

**Comment by vincenthz** [comment]
sorry, I'm lagging behind. I'll (finally) have a look at this tomorrow

**Comment by vincenthz** [comment]
alright. done and released in 0.2.9
