### ISSUE TITLE
ISO8601_DateAndTime example doesn't parse

### ISSUE THREAD

**Issue by kinoru** [vincenthz/hs-hourglass#30]
The documentation says

> ISO8601 Date and Time format string.
> 
> e.g. 2014-04-05T17:25:04+00:00 2014-04-05T17:25:04Z

but unlike the example above, it doesn't seem to correctly parse the ones that end with `Z`.

```haskell
*Data.Hourglass> timeParse ISO8601_DateAndTime "2014-04-05T17:25:04Z"
Nothing
```

Happens with both 0.2.10 (Stackage lts-6.4) and the current master (a469c91ea52131d548856a020861a206e40cecae). ... I think.

**Comment by NicolasDP** [comment]
Well spotted. and thank you for the PR.
Sorry for the delay in responding, @vincenthz and I have been quite busy on other projects.
