### ISSUE TITLE
Possible error in Real instance of ElapsedP

### ISSUE THREAD

**Issue by afcowie** [vincenthz/hs-hourglass#33]
I'm getting divide by zero errors. I have not tracked it down conclusively, but I'm using `realToFrac` to turn an ElapsedP into a POSIXTime (aka NominalDiffTime) per the instructions in Data.Time.Clock.POSIX and that led me to looking at [Time/Types.hs](https://github.com/vincenthz/hs-hourglass/blob/master/Time/Types.hs#L150) and the Real instance for ElapsedP

``` haskell
instance Real ElapsedP where
    -- FIXME
    toRational (ElapsedP (Elapsed (Seconds s)) (NanoSeconds ns)) =
        fromIntegral s + (1000000000 % fromIntegral ns)
```

where, eyeballing it, it seems the Rational constructor is backwards! I don't pretend to have analyzed this fully, but off the top of my head the case where the nanoseconds portion of an elapsed is `0` is a common case (and appears to be the situation in my test here).

Sorry I don't have a conclusive test to offer but I wanted to report right away.

AfC

P.S. A direct way to get a UTCTime out of a Timeable would be really useful. Right now I'm floundering around through (as you can see) POSIXTime and that's a bit messy.

**Comment by NicolasDP** [comment]
Hi, thank you for the bug report.

Indeed it seems that the nano second part is missing a value check in the case `ns` is `0`.

**Comment by NicolasDP** [comment]
About the conversion from/to `time` we have started the `Time.Compat` module with compatibility function from `time` to `hourglass`. I think it might be possible to write helpers to go the other way around.
