### ISSUE TITLE
Unix.hs compile error ->  Not in scope: data constructor `CTime'

### ISSUE THREAD

**Issue by stanleyxc** [vincenthz/hs-hourglass#8]
Apologies in advance if this is not a place to ask questions.    

I ran into this compile error trying to install hourglass via cabal. 
 >cabal install hourglass 

Building hourglass-0.2.6...
[1 of 13] ...
[2 of 13] ...
[3 of 13] ...
[ 4 of 13] Compiling Data.Hourglass.Internal.Unix ( Data/Hourglass/Internal/Unix.hs, dist/build/Data/Hourglass/Internal/Unix.o )

Data/Hourglass/Internal/Unix.hs:54:21:
    Not in scope: data constructor `CTime'

Data/Hourglass/Internal/Unix.hs:63:20:
    Not in scope: data constructor `CTime'

My system is CentOS release 6.4, with ghc 7.0.4, base-4.3.1.0

Any idea what else I am missing?

**Comment by NicolasDP** [comment]
I suppose this #16 might fix your issue with this old version of GHC.
